function [dataR, dataG, dataB] = readDataTLS(filename)
% AIM
% Reads the text file generated by TLS software containing the reflectance
% data profiles and put them in matrices depending on the RGB channels.
% 
% INPUT
% filename (str): indicates the path of the filename to read the data from.
% It should be a text file generated by the TLS software.
% 
% OUTPUTS
% dataR (mat): matrix of shape (512xnumRecords) containing information of
% the RED channel.
% dataG (mat): matrix of shape (512xnumRecords) containing information of
% the GREEN channel.
% dataB (mat): matrix of shape (512xnumRecords) containing information of
% the BLUE channel.

% The data is organised as follows:
% 1st line are NaN values as it is text in original file,
% In between each set of data (512 rows), two rows of NaN values due to
% text in original file.

file_table = readtable(filename);
tableRecords = file_table.(1);
numRecords = tableRecords(end);
numChannels = file_table.(2)(end);
tableData = file_table.(3);

data = zeros(numChannels, numRecords);

for i = 1:numRecords
    cond = find(tableRecords == i);
    data(:, i) = tableData(cond);
end

% Separation of data from RGB channels
dataR = data(:, 1:3:numRecords);
dataG = data(:, 2:3:numRecords);
dataB = data(:, 3:3:numRecords);

end